//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevoProfit.WebAssembly.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevoProfit.WebAssembly.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Statement.
        /// </summary>
        public static string AccountStatement {
            get {
                return ResourceManager.GetString("AccountStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount inserted.
        /// </summary>
        public static string AmountInDollars {
            get {
                return ResourceManager.GetString("AmountInDollars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amout in €.
        /// </summary>
        public static string AmountInEuros {
            get {
                return ResourceManager.GetString("AmountInEuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are using the Average Cost Basis Method. This is the method required by the French government for realized gains calculation..
        /// </summary>
        public static string Answer1 {
            get {
                return ResourceManager.GetString("Answer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, we do not store any personal data, trading data, and do not use cookies..
        /// </summary>
        public static string Answer2 {
            get {
                return ResourceManager.GetString("Answer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open your Revolut app and go to the &quot;Stocks&quot; section. Click on the &quot;...&quot; button and select &quot;Statement&quot; &gt; &quot;Account Statement&quot;. Choose the Excel format, and choose the dates from June 2017 to {0}..
        /// </summary>
        public static string Answer3 {
            get {
                return ResourceManager.GetString("Answer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average stock price.
        /// </summary>
        public static string AveragePrice {
            get {
                return ResourceManager.GetString("AveragePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ☕ Buy me a coffee.
        /// </summary>
        public static string BuyMeACoffee {
            get {
                return ResourceManager.GetString("BuyMeACoffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Top Up.
        /// </summary>
        public static string CashTopUp {
            get {
                return ResourceManager.GetString("CashTopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Withdrawal.
        /// </summary>
        public static string CashWithdrawal {
            get {
                return ResourceManager.GetString("CashWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Waltio Account Statement export file (.csv).
        /// </summary>
        public static string CryptoFile {
            get {
                return ResourceManager.GetString("CryptoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🪙 Crypto Lefts.
        /// </summary>
        public static string CryptoLefts {
            get {
                return ResourceManager.GetString("CryptoLefts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeton.
        /// </summary>
        public static string CryptoSymbol {
            get {
                return ResourceManager.GetString("CryptoSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custody Fee.
        /// </summary>
        public static string CustodyFee {
            get {
                return ResourceManager.GetString("CustodyFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevoProfit is not affiliated or associated any way with Revolut™ Ltd. The realized gain calculation is based on the Average Cost methodology. You should consult an accountant to validate the results and make sure they comply with your local tax authority rules..
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dividends.
        /// </summary>
        public static string Dividends {
            get {
                return ResourceManager.GetString("Dividends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did I save you time? You can thank me by donating below..
        /// </summary>
        public static string DonateBelow {
            get {
                return ResourceManager.GetString("DonateBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees.
        /// </summary>
        public static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gains.
        /// </summary>
        public static string Gains {
            get {
                return ResourceManager.GetString("Gains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gains in €.
        /// </summary>
        public static string GainsInEuros {
            get {
                return ResourceManager.GetString("GainsInEuros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong while reading the csv.
        /// </summary>
        public static string GeneralErrorMessage {
            get {
                return ResourceManager.GetString("GeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit &amp; Loss statement.
        /// </summary>
        public static string ProfitAndLossStatement {
            get {
                return ResourceManager.GetString("ProfitAndLossStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do we calculate realized gains?.
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you store my trading data?.
        /// </summary>
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How can I get my Revolut report in .csv format?.
        /// </summary>
        public static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results in {0}.
        /// </summary>
        public static string ResultsIn {
            get {
                return ResourceManager.GetString("ResultsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Revolut Account Statement export file (.csv).
        /// </summary>
        public static string RevolutFile {
            get {
                return ResourceManager.GetString("RevolutFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RevoProfit.
        /// </summary>
        public static string RevoProfit {
            get {
                return ResourceManager.GetString("RevoProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate you trading gains or loss on your Revolut Stocks trading account..
        /// </summary>
        public static string RevoProfitSubtitle {
            get {
                return ResourceManager.GetString("RevoProfitSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💸 See Results.
        /// </summary>
        public static string SeeResults {
            get {
                return ResourceManager.GetString("SeeResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 💰 Sell Order Details.
        /// </summary>
        public static string SellOrderDetails {
            get {
                return ResourceManager.GetString("SellOrderDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🚀 Stock Lefts.
        /// </summary>
        public static string StockLefts {
            get {
                return ResourceManager.GetString("StockLefts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker.
        /// </summary>
        public static string Ticker {
            get {
                return ResourceManager.GetString("Ticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WaltProfit.
        /// </summary>
        public static string WaltProfit {
            get {
                return ResourceManager.GetString("WaltProfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate you crypto gains or loss from your waltio.co export..
        /// </summary>
        public static string WaltProfitSubtitle {
            get {
                return ResourceManager.GetString("WaltProfitSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
