name: publish

on:
  push:
    branches: [ production ]

env:
  AZURE_WEBAPP_NAME: revoprofit

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Install dependencies
      run: dotnet restore
    
    - run: cd RevoProfit.WebAssembly
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish -c Release -o ${{ env.DOTNET_ROOT }}/dotnet-webapp -r linux-x64 --self-contained true /p:UseAppHost=true
    
    - uses: azure/webapps-deploy@v2
      name: Deploy
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: '${{ env.DOTNET_ROOT }}/dotnet-webapp'
