name: deploy github page

on:
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: RevoProfit.WebAssembly/RevoProfit.WebAssembly.csproj

    steps:
    - uses: actions/checkout@v2
    - run: dotnet publish $GITHUB_WORKSPACE/$PROJECT_PATH -c Release -o netapp
    - run: touch netapp/wwwroot/.nojekyll
    - run: echo "revoprofit.fr" > netapp/wwwroot/CNAME
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: netapp
        path: netapp

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4.1.7
      with:
        name: netapp
    - name: GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v4
      with:
        build_dir: wwwroot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}